# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 20:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import storage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=storage.utils.short_uuid, unique=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage('/Users/maxim/Projects/storage/uploads'), upload_to=storage.utils.ShardedUpload())),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
