# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='assets',
        ),
    ]
