# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 23:08
from __future__ import unicode_literals

import __main__
from django.db import migrations, models
import storage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20161103_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(storage=__main__.UploadStorage(), upload_to=storage.utils.ShardedUpload()),
        ),
    ]
